# Generated by Django 4.0.4 on 2022-05-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='count'),
        ),
    ]
